
---
title: "Course diary"
output:
  html_document:
    theme: sandstone
    highlight: tango
---


## First week: Tools and methods for open and reproducible research



I started this week's assignments by doing the DataCamp exercises (R Short and sweet) introducing me to the R language and the basics of Rstudio. I learned how to create objects, functions, and how to read data files as data frames consisting of multiple vectors. 


The DataCamp experience came in use when carrying out the first Rstudio exercise. I started the exercise by creating an account to GitHub and linking the account to the course project template using the "forking" operation. Then, I downloaded the SmartGit software to upload the R markdown files to my course repository (https://github.com/villehar/IODS-project). Before downloading the SmartGit I used couple of moments struggling with the GitHub destop (another software for the same purpose as the SmartGit) in order to acces the files (e.g. chapter1.Rmd) in the repository file. However, I did not manage to do so with GitHub destop and used SmartGit instead. 


Next, I opened the chapter1.Rmd file in Rstudio and wrote a short description of the course while using the Rmarkdown commands in order to create titles and *subtitles* as well as other adjustments to the text layout. Then I knitted the HTML document and checked that everything looked as it shoul.


In the third task, I opened the index.Rmd file in Rstudio and added author:"Your Name" below the title option in the R markdown syntax. I again finished the part by clicking the Knit button in the graphical interface of Rstudio.


In the fouth task, I created a new R markdown file. When opening the file, the system automatically added some example syntax on the page. After playing around with those syntaxes I removed all the exmaple code and added a new title (Course diary), subtitles (First Week) and wrote couple of lines about the course. When saving the new Rmd file to my IODS-project folder, I named is as README.Rmd as recuested. Finally, I changed the theme of the htlm codument to *sandstone* to changes the appearance of the page.


After finishing all the tasks, I uploaded the changes made to my local repository files to GitHub for futher evaluation. 


